# https://www.prestonlamb.com/blog/creating-a-docker-image-with-github-actions

name: Furlong CI

on: [push]

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      # checkout our code to use for the build
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
      - name: install deps
        run: |
          npm install
      - name: run tests
        run: |
          npm test
      - name: build
        run: |
          npm run build
